import Foundation

/// Produces shareable artefacts from a research session. Three formats:
///   - **Markdown** — human-readable; embeds the synthesis, inline `[N]` markers
///     intact, and a numbered Sources section.
///   - **HTML** — same content rendered as a self-contained HTML page styled
///     for printing or PDF export from Safari.
///   - **JSON** — full structured dump (query, turns, sources, citations) for
///     downstream tooling.
public enum SessionExporter {
    public enum Format: String, CaseIterable, Sendable, Identifiable {
        case markdown, html, json
        public var id: String { rawValue }
        public var fileExtension: String {
            switch self {
            case .markdown: "md"
            case .html: "html"
            case .json: "json"
            }
        }
        public var displayName: String {
            switch self {
            case .markdown: "Markdown"
            case .html: "HTML"
            case .json: "JSON"
            }
        }
    }

    public struct Payload: Sendable {
        public let suggestedFilename: String
        public let data: Data
        public let mimeType: String
    }

    public static func export(session: StoredSession, format: Format) throws -> Payload {
        switch format {
        case .markdown:
            let body = markdown(session: session)
            return Payload(suggestedFilename: filename(session: session, ext: "md"),
                          data: Data(body.utf8),
                          mimeType: "text/markdown")
        case .html:
            let body = html(session: session)
            return Payload(suggestedFilename: filename(session: session, ext: "html"),
                          data: Data(body.utf8),
                          mimeType: "text/html")
        case .json:
            let body = try json(session: session)
            return Payload(suggestedFilename: filename(session: session, ext: "json"),
                          data: body,
                          mimeType: "application/json")
        }
    }

    // MARK: - Markdown

    public static func markdown(session: StoredSession) -> String {
        var out = ""
        out += "# \(session.query)\n\n"
        out += "_Generated by Swift Deep Research — provider \(session.providerName), \(session.totalTokens) tokens, status \(session.status)_\n\n"
        let turns = session.turns.sorted(by: { $0.createdAt < $1.createdAt })
        for turn in turns {
            let label = turn.role == "user" ? "## Question" : "## Synthesis"
            out += "\(label)\n\n\(turn.markdown)\n\n"
        }
        if !session.sources.isEmpty {
            out += "\n---\n\n## Source archive\n\n"
            for (i, s) in session.sources.sorted(by: { $0.fetchedAt < $1.fetchedAt }).enumerated() {
                out += "\(i + 1). [\(s.title)](\(s.urlString))"
                if !s.providerHint.isEmpty { out += " — _\(s.providerHint)_" }
                out += "\n"
            }
        }
        return out
    }

    // MARK: - HTML

    public static func html(session: StoredSession) -> String {
        let title = escapeHTML(session.query)
        var body = ""
        for turn in session.turns.sorted(by: { $0.createdAt < $1.createdAt }) {
            let header = turn.role == "user" ? "Question" : "Synthesis"
            body += "<section class=\"turn turn-\(turn.role)\"><h2>\(header)</h2>"
            body += "<pre class=\"md\">\(escapeHTML(turn.markdown))</pre></section>"
        }
        var sources = ""
        if !session.sources.isEmpty {
            sources = "<section class=\"sources\"><h2>Source archive</h2><ol>"
            for s in session.sources.sorted(by: { $0.fetchedAt < $1.fetchedAt }) {
                sources += "<li><a href=\"\(escapeHTML(s.urlString))\">\(escapeHTML(s.title))</a>"
                if !s.providerHint.isEmpty { sources += " — <em>\(escapeHTML(s.providerHint))</em>" }
                sources += "</li>"
            }
            sources += "</ol></section>"
        }
        return """
        <!doctype html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <title>\(title)</title>
        <style>
        body { font: 15px/1.55 -apple-system, BlinkMacSystemFont, system-ui, sans-serif; max-width: 760px; margin: 40px auto; padding: 0 24px; color: #1d1d1f; }
        h1 { font-size: 28px; }
        h2 { font-size: 18px; margin-top: 28px; border-bottom: 1px solid #e5e5e7; padding-bottom: 4px; }
        pre.md { white-space: pre-wrap; word-wrap: break-word; font: inherit; }
        a { color: #0066cc; }
        .meta { color: #6e6e73; font-size: 12px; }
        .turn-user { background: #f5f5f7; padding: 16px; border-radius: 12px; }
        ol { padding-left: 1.5em; }
        </style>
        </head>
        <body>
        <h1>\(title)</h1>
        <p class="meta">Generated by Swift Deep Research • \(session.providerName) • \(session.totalTokens) tokens</p>
        \(body)
        \(sources)
        </body>
        </html>
        """
    }

    // MARK: - JSON

    public static func json(session: StoredSession) throws -> Data {
        struct Out: Encodable {
            let id: UUID
            let query: String
            let createdAt: Date
            let providerName: String
            let totalTokens: Int
            let status: String
            let turns: [Turn]
            let sources: [Source]

            struct Turn: Encodable {
                let role: String
                let markdown: String
                let createdAt: Date
                let citations: [Citation]
                struct Citation: Encodable {
                    let url: String
                    let title: String
                    let claim: String
                    let exactQuote: String
                }
            }
            struct Source: Encodable {
                let title: String
                let url: String
                let snippet: String
                let providerHint: String
                let fetchedAt: Date
            }
        }
        let out = Out(
            id: session.id,
            query: session.query,
            createdAt: session.createdAt,
            providerName: session.providerName,
            totalTokens: session.totalTokens,
            status: session.status,
            turns: session.turns.sorted(by: { $0.createdAt < $1.createdAt }).map { t in
                Out.Turn(
                    role: t.role,
                    markdown: t.markdown,
                    createdAt: t.createdAt,
                    citations: t.citations.map { c in
                        Out.Turn.Citation(
                            url: c.sourceURLString,
                            title: c.sourceTitle,
                            claim: c.claim,
                            exactQuote: c.exactQuote
                        )
                    }
                )
            },
            sources: session.sources.sorted(by: { $0.fetchedAt < $1.fetchedAt }).map {
                Out.Source(
                    title: $0.title,
                    url: $0.urlString,
                    snippet: $0.snippet,
                    providerHint: $0.providerHint,
                    fetchedAt: $0.fetchedAt
                )
            }
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        return try encoder.encode(out)
    }

    // MARK: - Helpers

    private static func filename(session: StoredSession, ext: String) -> String {
        let safe = session.query
            .lowercased()
            .replacingOccurrences(of: "[^a-z0-9]+", with: "-", options: .regularExpression)
            .trimmingCharacters(in: CharacterSet(charactersIn: "-"))
        let stub = String(safe.prefix(50))
        return stub.isEmpty ? "research.\(ext)" : "\(stub).\(ext)"
    }

    private static func escapeHTML(_ s: String) -> String {
        var out = s
        out = out.replacingOccurrences(of: "&", with: "&amp;")
        out = out.replacingOccurrences(of: "<", with: "&lt;")
        out = out.replacingOccurrences(of: ">", with: "&gt;")
        out = out.replacingOccurrences(of: "\"", with: "&quot;")
        return out
    }
}
